fix: Fix yarn not found

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -17,6 +17,14 @@ jobs:
     - name: Git Pull and Build on Droplet
       run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} <<'ENDSSH'
+          # Check if Yarn is installed, install if not
+          if ! command -v yarn &> /dev/null; then
+              echo "Yarn not found, installing..."
+              curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
+              echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
+              sudo apt-get update && sudo apt-get install yarn
+          fi
+          
           # Assuming you have a git repository cloned at /var/www/myapp
           cd /root/frontend
           
@@ -27,8 +35,8 @@ jobs:
           yarn install
           yarn build
           
-          # Optionally, move build artifacts to the desired location
-          # This step depends on your specific setup. For example, for a Vue app:
+          # Move build artifacts to the desired location
           rm -rf /var/www/html/quizzebassen/*
           cp -R dist/* /var/www/html/quizzebassen/
         ENDSSH
+
