refactor: Fix version 20

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -17,6 +17,32 @@ jobs:
     - name: Git Pull and Build on Droplet
       run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} <<'ENDSSH'
+          # Install NVM (Node Version Manager) if not already installed
+          if ! command -v nvm &> /dev/null; then
+              echo "NVM not found, installing..."
+              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
+              # This loads nvm
+              export NVM_DIR="$HOME/.nvm"
+              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+              [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
+          fi
+
+          # Load NVM scripts for this session
+          export NVM_DIR="$HOME/.nvm"
+          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
+
+          # Install and use Node.js version 20
+          nvm install 20
+          nvm use 20
+
+          # Verify Node and NPM versions
+          node -v
+          npm -v
+
+          # Assuming you have a git repository cloned at /var/www/myapp
+          cd /root/frontend
+          
           # Check if Yarn is installed, install if not
           if ! command -v yarn &> /dev/null; then
               echo "Yarn not found, installing..."
@@ -24,9 +50,6 @@ jobs:
               echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
               sudo apt-get update && sudo apt-get install yarn
           fi
-          
-          # Assuming you have a git repository cloned at /var/www/myapp
-          cd /root/frontend
           
           # Pull the latest changes
           git pull
@@ -39,4 +62,5 @@ jobs:
           rm -rf /var/www/html/quizzebassen/*
           cp -R dist/* /var/www/html/quizzebassen/
         ENDSSH
+
 
